name:                port
version:             0.1.0.0
github:              "mikewalrus/port"
license:             GPL-3.0-or-later
author:              "Liao Junxuan"
copyright:           "2022 Liao Junxuan"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            Extract port definitions from Verilog.
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mikewalrus/port#readme>

dependencies:
- base >= 4.7 && < 5
- parsec >= 3 && < 4
- optparse-applicative >= 0.16

library:
  source-dirs: src

executable:
  main:                Main.hs
  source-dirs:         app
  ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  dependencies:
  - port

tests:
  port-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - port
